### ISSUE TITLE
Want to sign the pledge, don't know what I'm doing here ;-)

### ISSUE THREAD

**Issue by joenatoli** [neveragaindottech/neveragaindottech.github.io#1178]
Sorry folks, I'm not a dev or programmer, everything here is greek to me. The email I sent to you bounced (no such gmail address). This issue is extremely important to me, and I'm grateful you started it — please tell me how to **add my name**.

**Comment by honeyjbear** [comment]
Joe - hopefully this will help until a moderator can give you assistance:

http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

**Comment by joenatoli** [comment]
Much appreciated @honeyjbear, although I'm still at a loss. I've never "forked a repo" in my life ;-) All the terms are foreign to me, and I don't want to waste everyone's time asking for a lesson. Thank you again for trying, though!

**Comment by honeyjbear** [comment]
Joe - try this - http://yangsu.github.io/pull-request-tutorial/ 

If you click on the link from the link it lands you on the page for the "forked repo" which is really a fancy way of saying file (way over simplified)

In the right hand column you should see a green button that says "New pull request"
Click that button
pick the file that says clean master and compare
It should take a few moments and then give you a page with the option to add comments

Follow the format of 

name: 
 -  link: 
 -  affiliation: 
 -  occupation_title: 
 -  github: 

Then click send pull request :)

**Comment by daveloyall** [comment]
## Signing by pull request

To sign [the pledge](http://neveragain.tech/), please submit a pull request:

1. Go to the [`_signatures`](/_signatures/) folder.
2. Click the "Create new file" button in the upper-right corner.
3. Name the file something unique, for example: `first_name_last_name_affiliation.md`. The filename must have `.md` at the end.
4. Copy the text of the [`template.md`](https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.md) file and paste it in the newly created signature file from step 3.
5. Edit the file to fill in the fields exactly as you want them to be shown.
6. Commit the file and make a pull request.
7. In your pull request description, include a link to a webpage you control that refers to your GitHub account.
8. A volunteer will verify that the person signing owns the submitting GitHub account, and then merge in your pull request.

--------

(That's how you do it on 2016-12-16.  If you're reading this much later, check https://github.com/neveragaindottech/neveragaindottech.github.io/blob/master/README.md for updates to these instructions.)

**Comment by lizthegrey** [comment]
Please use https://sign.neveragain.tech if you are not familiar with git/markdown and want to use Twitter. It looks like you have twitter.com/joenatoli which can be used for signing in.
