### ISSUE TITLE
Should I sign if I'm a student with no formal job?

### ISSUE THREAD

**Issue by strugee** [neveragaindottech/neveragaindottech.github.io#1376]
Heya,

I'm a big fan of this initiative and I'm considering signing. However, while I'm quite active in the software community (in particular with http://pump.io, which uses social data) and plan to work in software in the future, I've never held a formal programming job for longer than two months.

Should I sign? I don't want to dilute the message if I'm not part of the intended audience, especially since the homepage begins with:

> We, the undersigned, are employees of tech organizations and companies based in the United States. We are engineers, designers, business executives, and others whose jobs include managing or processing data about people.

**Comment by ryanprior** [comment]
If you are active in pump.io, then for the purposes of this statement that is one of your jobs. The fact that it isn't providing a major source of income is secondary; like you said, as a member of that community you have the opportunity to make change for better or worse & I hope we can count on you in this struggle.

**Comment by strugee** [comment]
@ryanprior great, that's phenomenal.

**Comment by heliostatic** [comment]
Good question and resolution. Closed merged.
