### ISSUE TITLE
Is it https or http?

### ISSUE THREAD

**Issue by rakibtg** [neveragaindottech/neveragaindottech.github.io#1558]
The repository description at top is pointing to https://neveragain.tech/, which raises a security warning in browser, it seems that the SSL is not valid, please fix the link to http ( http://neveragain.tech/ )

**Comment by ryanprior** [comment]
Thanks for noticing that and opening an issue, @rakibtg. There is some relevant discussion in #46.

**Comment by rakibtg** [comment]
@ryanprior I think many non-tech'y people would found it ambiguous, as it is just a static site a quick fix would be to link to the http version of the domain..

**Comment by ryanprior** [comment]
Unfortunately, that link is part of the repository description and not part of the static site, so we can't open a pull request to fix it.

**Comment by rakibtg** [comment]
Exactly!

**Comment by lizthegrey** [comment]
Fixed.
