### ISSUE TITLE
Suppose people sign, then the pledge is patched.  Now what?

### ISSUE THREAD

**Issue by daveloyall** [neveragaindottech/neveragaindottech.github.io#1579]
> [...] it's worth pointing out that you should probably get everybody who signed the list already to reaffirm their commitment to the amended text or remove their name (similar to the procedure around changing licenses without a CLA).

(That is from https://github.com/neveragaindottech/neveragaindottech.github.io/issues/52#issuecomment-266929108)

So, let's make a call on this.  Do you leave the pledge as-is, forever more?  Or do you figure out how to change it without inciting a backlash from the existing signatories?

I'm in favor of leaving it as is, because I don't want to destroy current momentum.  Regrettably, this means that I'm removing my thumbs up on the proposal to add gender identity etc to the pledge. :(

**Comment by aem** [comment]
I definitely agree a pledge that has already been signed should not be modified without the approval of prior signers. On the other hand, part of the pledge is currently meaningless for many of its signers, so if it's not modified then it excludes lots of people. 

I suppose a "v2" pledge and allowing signers to move their name from v1 to v2 would just create too much confusion?

**Comment by lizthegrey** [comment]
@hypatia and @zestyping have stated that the original pledge text will *not* be modified and is immutable. We will not accept pull requests (except typographic/formatting) to the pledge text.
