### ISSUE TITLE
please collect follow-up contact info

### ISSUE THREAD

**Issue by brahn** [neveragaindottech/neveragaindottech.github.io#1856]
(Originally filed as https://github.com/lizthegrey/signbot/issues/15 , @lizthegrey  suggested reposting here)

Please forgive me if this is obvious/redundant/already discussed, I can only see what's on the site.

I think it's really important to collect email addresses so you can follow-up with signatories about what's happening, follow-on actions, etc. The pledge is a great starting point for building a community of tech folks who want to take further action. I would be really sad if this opportunity fell through the cracks.

Of course, there's no current mechanism to store contents other than the public repo, and I imagine many people would not want their email in there, so there'd need some sort of private backend (db, private github repo, even just logging where one could extract later).

Please let me know if this direction would be welcome, etc. Happy to help however I can.

**Comment by DanToml** [comment]
These are also stored in the git commits, but people haven't given explicit permission to use them.

**Comment by lizthegrey** [comment]
We're publishing a follow-on letter we hope people will see and direction people to work with their companies and local organizations as a follow-on step.
