### ISSUE TITLE
neveragain.tech is down

### ISSUE THREAD

**Issue by strugee** [neveragaindottech/neveragaindottech.github.io#2586]
Seems like maybe this domain got bought by someone else? Not sure, I'm on mobile so I can't investigate thoroughly.

**Comment by drewcassidy** [comment]
it looks like something is broken and jekyll is just showing the footer

**Comment by strugee** [comment]
@drewcassidy you don't see a Namecheap landing page at http://neveragain.tech/?

**Comment by drewcassidy** [comment]
oh I see what you mean, with the Parkingcrew link, yeah I think the domain got bought.

**Comment by strugee** [comment]
yep :/

**Comment by hypatia** [comment]
Sorry about that, I renewed the domain just now and it's back up. I set it to auto-renew, as well.

**Comment by strugee** [comment]
@hypatia <3 thanks!

Heard about IBM attending ICE conferences on "extreme vetting" software and got real nervous, so I went to read the neveragain header and noticed it was down. In any case thanks again for your quick response!
