### ISSUE TITLE
Some names are being dropped by subsequent merge commits

### ISSUE THREAD

**Issue by cesium12** [neveragaindottech/neveragaindottech.github.io#320]
For example, I added my name in dc797a3c but it was immediately removed in b6d31e07. (I'm assuming this was not intentional.)

I can't make heads or tails of the commit history because of all the merges, so I initially had some hope that the file was eventually consistent, but this does not appear to be the case.

**Comment by emhoracek** [comment]
I'm checking the diffs before merging... is there any way diffs could be "lying"?

**Comment by stuartpb** [comment]
If you're doing it via GitHub's merge UI, yeah, probably.

FWIW, my name appears to have been cut in that merge as well.

**Comment by cesium12** [comment]
Is it possible that the multiple maintainers trying to merge pull requests concurrently are writing over each other?

**Comment by hurtstotouchfire** [comment]
Is it possible that https://github.com/neveragaindottech/neveragaindottech.github.io/pull/228 would fix this?

**Comment by stuartpb** [comment]
It's possible (though it wouldn't fix it *retroactively*, of course). I'm not privy to the inner workings of GitHub's featureset.

More likely, though, is that it's a matter of commits being authored based on the tip of `master` at the time the merge page was loaded, meaning that the conflicts in question won't be observed, period.

**Comment by hurtstotouchfire** [comment]
I'm not sure that this is related. The PRs won't be mergeable if there are conflicts. I think this PR would just make there be less conflicts perhaps? I'm not sure if it affects GH's mergeability policy.

**Comment by stuartpb** [comment]
@hurtstotouchfire I think you meant to comment that on #228 itself

**Comment by hurtstotouchfire** [comment]
My suspicion is that this is just user error. I've never had this problem with the github merge ui before. Not invisibly anyway.

**Comment by stuartpb** [comment]
Yeah, I think https://github.com/neveragaindottech/neveragaindottech.github.io/issues/320#issuecomment-266933181 is probably accurate - one maintainer opens a PR merge based on the current master, another maintainer opens another merge based on the same master, and the content of the second merge overrides the first one.

**Comment by stuartpb** [comment]
In other words, I think it's a GitHub bug, based on their merge functionality not having been written to handle a potential race between two separate merges.

**Comment by stuartpb** [comment]
I've contacted GitHub support about this.

**Comment by mezz** [comment]
This happened the first time I tried to commit. It took me a little while to edit the page from the Github interface, and by the time I went to merge it was 1 added line and 2 (recent) lines removed. 

I abandoned that commit and made a new one more quickly and had no issue.

**Comment by hurtstotouchfire** [comment]
Yeah I think the github UI is causing issues. Some of these deletions were introduced by resolving conflicts in the web UI.

**Comment by stuartpb** [comment]
#376 didn't fix this; there are still a *lot* of names missing from the list (mine, for one).

**Comment by cesium12** [comment]
As well as mine. :P

**Comment by danielquinn** [comment]
@stuartpb and @cesium12 now that the project has changed to using individual files rather than editing a single document, this problem should go away.  I suppose you could just re-add your names now using the new system.

**Comment by stuartpb** [comment]
It would also be fixed the old way, as GitHub fixed the underlying bug after I pinged support about it:
