### ISSUE TITLE
Vague wording on data collection/retention

### ISSUE THREAD

**Issue by bbangert** [neveragaindottech/neveragaindottech.github.io#961]
One of the first bullet points:

> to minimize the collection and retention of data that would facilitate...

That doesn't actually require they cease the collection or retention of data that would be completely sufficient to identify chosen target groups, merely "minimize" it which is quite subjective. Why not call for a complete halt of the acquisition of data that could be used to target groups for unethical actions?

**Comment by lizthegrey** [comment]
See #1579 - the text cannot be updated. You are welcome to fork and reset the signatories list.
